global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'qvue7@soscandia.org'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'your_email@example.com'
    auth_password: 'your_email_password'
    require_tls: true
