version: "3.7"
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true" # Разрешает доступ к панели управления
      - "--providers.docker=true" # Включает поддержку Docker провайдера
      - "--entryPoints.web.address=:80" # Настройка точки входа на порт 80
    ports:
      - "80:80" # Открывает порт 80 для HTTP
      - "8080:8080" # Открывает порт 8080 для панели управления Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Доступ к Docker API

  backend1:
    image: nginx
    container_name: backend1
    labels:
      - "traefik.http.routers.backend1.rule=Host(`localhost`)"
      - "traefik.http.services.backend1.loadbalancer.server.port=80"
    ports:
      - "8081:80" # Проброс порта 8081 на порт 80 контейнера
    volumes:
      - "./custom-nginx.conf:/etc/nginx/nginx.conf"

  backend2:
    image: nginx
    container_name: backend2
    labels:
      - "traefik.http.routers.backend2.rule=Host(`localhost`)"
      - "traefik.http.services.backend2.loadbalancer.server.port=80"
    ports:
      - "8082:80" # Проброс порта 8082 на порт 80 контейнера
    volumes:
      - "./custom-nginx.conf:/etc/nginx/nginx.conf"
