
hashtable: hashtable.c hashtable.h
	gcc -Wall -o hashtable hashtable.c

bstree: bstree.c bstree.h
	gcc -Wall -o bstree bstree.c

hashtable_run: hashtable
	./hashtable

bstree_run: bstree
	./bstree

clean:
	rm -rf hashtable bstree
