version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - "5432:5432"

