replicaCount: 2
image:
  repository: nginx
  tag: latest  # Добавлено значение для версии образа
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: ImplementationSpecific
serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80